on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HOME_DISPLAY_CALENDAR_URLS: ""
      HOME_DISPLAY_WIFI_SSID: ""
      HOME_DISPLAY_WIFI_PSK: ""
      HOME_DISPLAY_INFLUX_HOST: ""
      HOME_DISPLAY_INFLUX_USER: ""
      HOME_DISPLAY_INFLUX_PASS: ""

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.2.3
          elixir-version: 1.11.3

      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-mix-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-build-

      - run: apt-get update && apt-get install pkgconf libglfw3 libglfw3-dev libglew2.1 libglew-dev
      - run: mix archive.install hex nerves_bootstrap --force
      - run: mix deps.get
      - run: mix test
      - run: mix credo --strict
      - run: mix dialyzer
